[package]
name = "adv-rs-2019"
version = "0.1.0"
authors = ["Marc Noirot <marc.noirot@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
itertools = "0.8.2"

[build-dependencies]
chrono = "0.4"
